title: Jules Moorhouse
description: My Personal Blog
author: Jules Moorhouse

url: "https://www.julesmoorhouse.com"

#logo: /hcz-jekyll-blog/static/img/avatar.png
logo: /static/img/me.png


github: https://github.com/jules2010
about: Software developer

destination: docs/

#baseurl: "/web"
#baseurl: ""

allowsearch: true

#disqus_shortname: aboutashu
#google_analytics: UA-72862926-1

share:
  twitter_username: \#
#  fb_appid: 000000000000

collections:
  stt_userguides:
    output: true
    permalink: /stt/userguides/:name
  stt_features:
    output: true
    permalink: /stt/features/:name
  bg_features:
    output: true
    permalink: /bg/features/:name

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
plugins: 
  - jekyll-paginate
  - jekyll-gist

reCaptcha:
  enabled: true
  siteKey: "6Ldjd5MUAAAAACSpMOcyQCUug3RNRov2GFyHC8r5"
  secret: "6Ldjd5MUAAAAACoejsRzB0Sy7L6AmR3wbSSiizrY"
  
# v3  siteKey: "6LftdpMUAAAAAHgwXamlqJdFTyWoXxNA85-_ibH5"
# v3  secret: "6LftdpMUAAAAAL_HkrXObdp2NGEAY0QATm8fCPvQ"

staticman:
  allowedFields          : ['name', 'email', 'url', 'message', 'replying_to']
  branch                 : "master"
  commitMessage          : "{fields.name}"
  pullRequestBody        : "Here's a new comment waiting for approval. <br/><br/>"
  filename               : entry{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "/_data/comments/{options.slug}" # (default)
  requiredFields         : ['name', 'email', 'message'] #replying_to can genuinely be blank
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # (default) "timestamp-seconds", "timestamp-milliseconds"
  endpoint               : "https://dev.staticman.net/v3/entry/github/" # URL of your own deployment with trailing slash, will fallback to the public instance
